services:

  backend:
    build: .
    restart: unless-stopped
    ports:
      - 8085:8085
    env_file: .env
    environment:
      MONGODB_URL: mongodb://root:supers3cret@mongo:27017/RaidBattle
      PORT: 8085

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supers3cret
      MONGO_INITDB_DATABASE: RaidBattle
    volumes:
      - mongodata:/data/db
      - ./docker/mongo/initdb.d:/docker-entrypoint-initdb.d:ro

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: supers3cret
      ME_CONFIG_MONGODB_URL: mongodb://root:supers3cret@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodata:
